global using FluentAssertions;
global using MockMethodCallOrderVerifier;
global using Moq;
global using TextTemplateProcessor.Core;
global using TextTemplateProcessor.Interfaces;
global using TextTemplateProcessor.TestShared;
global using Xunit;
global using static TextTemplateProcessor.Core.Messages;
global using static TextTemplateProcessor.TestShared.Globals;
global using static TextTemplateProcessor.TestShared.MethodCallTokens;
